# ReadTheDocs build configuration
# See: https://docs.readthedocs.io/en/stable/config-file/v2/

version: 2

build:
  os: ubuntu-20.04
  tools:
    python: "3.10"

python:
  version: 3.10
  install:
    - method: pip
      path: .
      extra: dev

sphinx:
  configuration: docs/conf.py
  fail_on_warning: false

formats:
  - epub
  - pdf

# Optional: Enable PDF builds
# pdf:
#   enabled: true
